### PR TITLE
[Breaking change]Update arcsong.json

### PR DESCRIPTION
**Pull request by jasonren0403**
Keep pure songlist item in arcsong.json, prevent extra-step parsing

### CODE REVIEW

**Comment by jasonren0403** [comment]
ping @Awbugl for review

**Comment by Awbugl** [comment]
Github told me there’re 49,367 changes XD

**Comment by Awbugl** [comment]
personally, I think it would be easier to parse in keeping consistent with the AUA - especially after this has been going on for a long time. Let me ask @TheSnowfield for her thoughts.

**Comment by jasonren0403** [comment]
maybe we could separate large json with song packs to prevent too much change towards single file

**Comment by Awbugl** [comment]
> maybe we could separate large json with song packs to prevent too much change towards single file

that makes sense. I'll add that feature to the aua.

**Pull request merged**
